// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_Ex_3.Models;

namespace WebApp_Ex_3.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201127215701_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApp_Ex_3.Models.Condominio", b =>
                {
                    b.Property<int>("Id_Condominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Condominio");

                    b.ToTable("Condominios");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Familia", b =>
                {
                    b.Property<int>("Id_Familia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Apto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Condominio")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Familia");

                    b.HasIndex("Id_Condominio");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Morador", b =>
                {
                    b.Property<int>("Id_Morador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id_Familia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdBichos")
                        .HasColumnType("int");

                    b.HasKey("Id_Morador");

                    b.HasIndex("Id_Familia");

                    b.ToTable("Moradors");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Familia", b =>
                {
                    b.HasOne("WebApp_Ex_3.Models.Condominio", "condominio")
                        .WithMany("Familias")
                        .HasForeignKey("Id_Condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("condominio");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Morador", b =>
                {
                    b.HasOne("WebApp_Ex_3.Models.Familia", "familia")
                        .WithMany("Moradors")
                        .HasForeignKey("Id_Familia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("familia");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Condominio", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("WebApp_Ex_3.Models.Familia", b =>
                {
                    b.Navigation("Moradors");
                });
#pragma warning restore 612, 618
        }
    }
}
